---
  - name: "Installing Control Node Libraries"
    hosts: localhost
    become: yes
    
    connection: local
    tasks:
    - name: Add Beegfs packages
      get_url:
        url: https://www.beegfs.io/release/beegfs_7.2/dists/beegfs-deb10.list
        dest: /etc/apt/sources.list.d

    - name: Get Beegfs apt key
      ansible.builtin.apt_key:
        url: https://www.beegfs.io/release/beegfs_7.2/gpg/DEB-GPG-KEY-beegfs
        state: present

    - name: update apt list
      apt:
        update_cache: yes

    - name: Downloading and installing packages
      apt:
        name: ['munge', 'libmunge-dev', 'gcc', 'gpp', 'g++', 'gfortran', 'make', 'libevent-dev', 'libhwloc-dev', mariadb-server, libmariadb-dev, libmariadbclient-dev, python3-pip, ntp]  
        state: present
        
    - name: Installing Beegfs packages
      apt:
        name: ['beegfs-mgmtd', 'beegfs-meta', beegfs-client', 'beegfs-helperd', 'beegfs-utils']  
        state: present


    